version: '3.8'

services:
# use the production version of client_app
  client_app:
    image: kenlongdocker/client_app:production
    container_name: client_app
    ports:
      - "9000:9000"
    networks:
      - app-network

# use the new version of the calculator_app
  calculator_app:
    image: kenlongdocker/calculator_app:latest
    container_name: calculator_app
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
