version: '3.8'

services:
  client_app:
    image: kenlongdocker/client_app:latest
    container_name: client_app
    ports:
      - "9000:9000"
    environment:
      - CALCULATOR_URL=http://calculator_app:8000  # Use the service name as hostname
    networks:
      - app-network

  calculator_app:
    image: kenlongdocker/calculator_app:production
    container_name: calculator_app
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
