version: '3.8'

services:
  client_app:
    image: kenlongdocker/client_app:develop
    container_name: client_app
    ports:
      - "9000:9000"
    environment:
      - CALCULATOR_URL=http://calculator_app:8000  # Use the service name as hostname
    networks:
      - app-network

  calculator_app:
    image: kenlongdocker/calculator_app:production
    container_name: calculator_app
    ports:
      - "8000:8000"
    networks:
      - app-network

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - app-network

  chrome-node:
    image: selenium/node-chrome:latest
    container_name: chrome-node
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    networks:
      - app-network

  firefox-node:
    image: selenium/node-firefox:latest
    container_name: firefox-node
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
